---
- name: "Debian Derivates: Download host-specific Checkmk CEE Agent."
  ansible.builtin.uri:
    url: "{{ checkmk_agent_agent.url.cee }}?host_name={{ inventory_hostname }}&os_type=linux_deb&agent_type=host_name"
    dest: "{{ checkmk_agent_agent.file.host }}"
    method: GET
    headers:
      Authorization: "Bearer {{ automation_user }} {{ automation_secret }}"
      Accept: "application/octet-stream"
  when: checkmk_agent_edition == "cee"
  register: checkmk_agent_download_state
  # This task may fail, as we fall back to the generic agent in that case
  failed_when: 'false'
  changed_when: 'false'

- name: "Debian Derivates: Install host-specific Checkmk CEE Agent."
  become: true
  ansible.builtin.apt:
    deb: "{{ checkmk_agent_agent.file.host }}"
    state: present
  when: (checkmk_agent_edition == "cee") and checkmk_agent_download_state.status == 200

- name: "Debian Derivates: Download GENERIC Checkmk CEE Agent."
  ansible.builtin.uri:
    url: "{{ checkmk_agent_agent.url.cee }}?os_type=linux_deb&agent_type=generic"
    dest: "{{ checkmk_agent_agent.file.cee }}"
    method: GET
    headers:
      Authorization: "Bearer {{ automation_user }} {{ automation_secret }}"
      Accept: "application/octet-stream"
  when: (checkmk_agent_edition == "cee") and checkmk_agent_download_state.status != 200

- name: "Debian Derivates: Install GENERIC Checkmk CEE Agent."
  become: true
  ansible.builtin.apt:
    deb: "{{ checkmk_agent_agent.file.cee }}"
    state: present
  when: (checkmk_agent_edition == "cee") and checkmk_agent_download_state.status != 200

- name: "Debian Derivates: Install Checkmk CRE Agent."
  become: true
  ansible.builtin.apt:
    deb: "{{ checkmk_agent_agent.file.cre }}"
    state: present
  when: checkmk_agent_edition == "cre"
