---
- name: "Download Checkmk CEE Agent for {{ inventory_hostname }}."
  ansible.builtin.uri:
    url: "{{ checkmk_agent_agent.url.cee }}?host_name={{ inventory_hostname }}&os_type=linux_deb&agent_type=host_name"
    dest: "{{ checkmk_agent_agent.file.host }}"
    method: GET
    headers:
      Authorization: "Bearer {{ automation_user }} {{ automation_secret }}"
      Accept: "application/octet-stream"
  when: checkmk_agent_edition == "cee"
  register: checkmk_host_agent_download_state
  # This task may fail, as we fall back to the generic agent in that case
  failed_when: 'false'
  changed_when: 'false'

- name: "Download Checkmk CEE Agent GENERIC."
  ansible.builtin.uri:
    url: "{{ checkmk_agent_agent.url.cee }}?os_type=linux_deb&agent_type=generic"
    dest: "{{ checkmk_agent_agent.file.cee }}"
    method: GET
    headers:
      Authorization: "Bearer {{ automation_user }} {{ automation_secret }}"
      Accept: "application/octet-stream"
  when: (checkmk_agent_edition == "cee") and checkmk_host_agent_download_state.failed | bool

- name: "Install Checkmk CEE Agent GENERIC on Debian Derivates."
  become: 'yes'
  ansible.builtin.apt:
      deb: "{{ checkmk_agent_agent.file.cee }}"
      state: present
  when: (checkmk_agent_edition == "cee") and checkmk_host_agent_download_state.failed | bool

- name: "Install Checkmk CEE Agent host-specific on Debian Derivates."
  become: 'yes'
  ansible.builtin.apt:
      deb: "{{ checkmk_agent_agent.file.host }}"
      state: present
  when: (checkmk_agent_edition == "cee") and not checkmk_host_agent_download_state.failed | bool

- name: "Install Checkmk CRE Agent on Debian Derivates."
  become: 'yes'
  ansible.builtin.apt:
      deb: "{{ checkmk_agent_agent.file.cre }}"
      state: present
  when: checkmk_agent_edition == "cre"
