---
- name: "Install xinetd"
  ansible.builtin.package:
    name: xinetd
    state: present
  tags:
    - install-package
    - install-prerequisites

- name: "Enable xinetd"
  ansible.builtin.service:
    name: xinetd
    state: started
    enabled: true
  tags:
    - enable-xinetd
