---
- name: "{{ ansible_system }}: Install xinetd"
  become: true
  ansible.builtin.package:
    name: xinetd
    state: present
  tags:
    - install-package
    - install-prerequisites

- name: "{{ ansible_system }}: Enable xinetd"
  become: true
  ansible.builtin.service:
    name: xinetd
    state: started
    enabled: true
  tags:
    - enable-xinetd
