---
- name: "Install xinetd"
  ansible.builtin.package:
    name: xinetd
    state: present
  tags:
    - install_package

- name: "Enable xinetd"
  ansible.builtin.service:
    name: xinetd
    state: started
    enabled: true
  tags:
    - enable_service
