---
- name: "Include OS family specific variables."
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - include-os-family-vars

- name: "({{ ansible_system }}): Include OS specific tasks."
  ansible.builtin.include_tasks: "{{ ansible_system }}.yml"
  tags:
    - include-system-tasks

- name: "Discover services and labels on host."
  checkmk.general.discovery:
    server_url: "{{ checkmk_agent_protocol }}://{{ checkmk_agent_server }}:{{ checkmk_agent_port }}/"
    site: "{{ checkmk_agent_site }}"
    validate_certs: "{{ checkmk_agent_server_validate_certs | bool }}"
    automation_user: "{{ checkmk_agent_user }}"
    automation_secret: "{{ checkmk_agent_auth }}"
    host_name: "{{ checkmk_agent_host_name }}"
    state: "fix_all"
  delegate_to: "{{ checkmk_agent_delegate_api_calls }}"
  when: checkmk_agent_discover | bool
  notify: "activate changes"
