---
- name: "Include Derivate specific Variables."
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Download Checkmk CRE Agent."
  get_url:
    url: "{{ checkmk_agent.url.cre }}"
    dest: "{{ checkmk_agent.file.cre }}"
  when: checkmk_edition == "cre"

# Not implemented yet, needs API
# https://docs.checkmk.com/master/de/agent_linux.html
# root@linux# curl -OJG "mycmkserver/mysite/check_mk/api/1.0/domain-types/agent/actions/download/invoke"; \
# --header 'Accept: application/octet-stream' \
# --header 'Authorization: Bearer automation myautomationsecret' \
# --data-urlencode 'os_type=linux_deb'
- name: "Download Checkmk CEE Agent."
  get_url:
    url: "{{ checkmk_agent.url.cee }}"
    dest: "{{ checkmk_agent.file.cre }}"
  when: checkmk_edition == "cee"

- name: "Run OS Family specific Tasks."
  include_tasks: "{{ ansible_os_family }}.yml"
