---
- name: "RedHat Derivates: Download host-specific Checkmk CEE Agent."
  ansible.builtin.uri:
    url: "{{ checkmk_agent_agent.url.cee }}?host_name={{ inventory_hostname }}&os_type=linux_rpm&agent_type=host_name"
    dest: "{{ checkmk_agent_agent.file.host }}"
    method: GET
    headers:
      Authorization: "Bearer {{ automation_user }} {{ automation_secret }}"
      Accept: "application/octet-stream"
  when: checkmk_agent_edition == "cee"
  register: checkmk_agent_download_state
  # This task may fail, as we fall back to the generic agent in that case
  failed_when: 'false'
  changed_when: 'false'

- name: "RedHat Derivates: Install host-specific Checkmk CEE Agent."
  become: true
  ansible.builtin.yum:
    name: "{{ checkmk_agent_agent.file.host }}"
    state: present
    disable_gpg_check: true
  when: (checkmk_agent_edition == "cee") and checkmk_agent_download_state.status == 200

- name: "RedHat Derivates: Download GENERIC Checkmk CEE Agent."
  ansible.builtin.uri:
    url: "{{ checkmk_agent_agent.url.cee }}?os_type=linux_rpm&agent_type=generic"
    dest: "{{ checkmk_agent_agent.file.cee }}"
    method: GET
    headers:
      Authorization: "Bearer {{ automation_user }} {{ automation_secret }}"
      Accept: "application/octet-stream"
  when: (checkmk_agent_edition == "cee") and checkmk_agent_download_state.status != 200

- name: "RedHat Derivates: Install Checkmk CRE Agent."
  become: true
  ansible.builtin.yum:
    name: "{{ checkmk_agent_agent.file.cre }}"
    state: present
    disable_gpg_check: true
  when: checkmk_agent_edition == "cre"

- name: "RedHat Derivates: Install GENERIC Checkmk CEE Agent."
  become: true
  ansible.builtin.yum:
    name: "{{ checkmk_agent_agent.file.cee }}"
    state: present
    disable_gpg_check: true
  when: (checkmk_agent_edition == "cee") and checkmk_agent_download_state.status != 200

- name: "RedHat Derivates: Install Checkmk CRE Agent."
  become: true
  ansible.builtin.yum:
    name: "{{ checkmk_agent_agent.file.cre }}"
    state: present
    disable_gpg_check: true
  when: checkmk_agent_edition == "cre"

- block:
  - name: "Check if checkmk_agent_server is an IP address."
    set_fact:
      checkmk_agent_server_ip: "{{ checkmk_agent_server }}"
    when: checkmk_agent_server_ip is not defined and checkmk_agent_server | ipaddr()

  - name: "Allow Checkmk services access to the agent."
    firewalld:
      permanent: 'yes'
      immediate: 'yes'
      state: enabled
      rich_rule: 'rule family="ipv4" source address={{ checkmk_agent_server_ip }} port port="6556" protocol="tcp" accept'
    when: checkmk_agent_server_ip is defined
    ignore_errors: true
    become: true
  when: checkmk_agent_configure_firewall | bool
