---
- name: "Install Checkmk CRE Agent on Suse Derivates."
  become: 'yes'
  ansible.builtin.zypper:
      name: "{{ checkmk_agent.file.cre }}"
      state: present
      disable_gpg_check: yes
  when: checkmk_edition == "cre"
