---
- name: "{{ ansible_os_family }} Derivatives: Install host-specific {{ checkmk_agent_edition | upper }} Agent."
  become: true
  community.general.zypper:
    name: "{{ checkmk_agent_agent.file.host }}"
    force: "{{ checkmk_agent_force_install | bool }}"
    state: present
    disable_gpg_check: true
  when: |
    checkmk_agent_edition | lower != "cre"
    and checkmk_agent_host_specific | bool
  tags:
    - install-package

- name: "{{ ansible_os_family }} Derivatives: Install GENERIC or folder-specific {{ checkmk_agent_edition | upper }} Agent."
  become: true
  community.general.zypper:
    name: "{{ checkmk_agent_agent.file.cee }}"
    force: "{{ checkmk_agent_force_install | bool }}"
    state: present
    disable_gpg_check: true
  when: |
    checkmk_agent_edition | lower != "cre"
    and not checkmk_agent_host_specific | bool
  tags:
    - install-package

- name: "{{ ansible_os_family }} Derivatives: Install Checkmk {{ checkmk_agent_edition | upper }} Agent."
  become: true
  community.general.zypper:
    name: "{{ checkmk_agent_agent.file.cre }}"
    force: "{{ checkmk_agent_force_install | bool }}"
    state: present
    disable_gpg_check: true
  when: checkmk_agent_edition | lower == "cre"
  tags:
    - install-package
