---
- name: "Install Checkmk CRE Agent on Suse Derivates."
  become: 'yes'
  zypper:
      name: "{{ checkmk_agent.file.cre }}"
      state: present
      disable_gpg_check: yes
  when: checkmk_edition == "cre"

- name: "Install Checkmk CEE Agent on Suse Derivates."
  become: 'yes'
  zypper:
      name: "{{ checkmk_agent.file.cee }}"
      state: present
      disable_gpg_check: yes
  when: checkmk_edition == "cee"
