---
- name: "{{ ansible_os_family }}: Download Checkmk CRE Agent."
  ansible.windows.win_get_url:
    url: "{{ checkmk_agent_agent.url.cre }}"
    validate_certs: "{{ checkmk_agent_server_validate_certs | bool }}"
    dest: "{{ checkmk_agent_agent.file.cre }}"
  when: checkmk_agent_edition == "cre"
  register: result
  retries: 3
  delay: 10
  until: "result.changed | bool"
  tags:
    - download-package

- name: "{{ ansible_os_family }}: Download host-specific Checkmk {{ checkmk_agent_edition | upper }} Agent."
  ansible.windows.win_get_url:
    url: "{{ checkmk_agent_agent.url.cee }}?host_name={{ checkmk_agent_host_name }}&os_type=windows_msi&agent_type=host_name"
    validate_certs: "{{ checkmk_agent_server_validate_certs | bool }}"
    dest: "{{ checkmk_agent_agent.file.host }}"
    method: GET
    headers:
      Authorization: "Bearer {{ checkmk_agent_user }} {{ checkmk_agent_auth }}"
      Accept: "application/octet-stream"
  when: |
    checkmk_agent_edition == "cee" or
    checkmk_agent_edition == "cce" or
    checkmk_agent_edition == "cfe" or
    checkmk_agent_edition == "cme"
  register: checkmk_agent_host_download_state
  # This task may fail, as we fall back to the generic agent in that case
  failed_when: 'false'
  changed_when: checkmk_agent_host_download_state.status_code is defined and checkmk_agent_host_download_state.status_code == 200
  delegate_to: "{{ checkmk_agent_delegate_download }}"
  tags:
    - download-package

- name: "Set Fact: Agent State: host-specific."
  ansible.builtin.set_fact:
    checkmk_agent_host_specific: >-
      {{ (checkmk_agent_host_download_state.status_code is defined and checkmk_agent_host_download_state.status_code == 200) | bool }}

- name: "{{ ansible_os_family }}: Install host-specific Checkmk {{ checkmk_agent_edition | upper }} Agent."
  ansible.windows.win_package:
    path: "{{ checkmk_agent_agent.file.host }}"
    state: present
  when: |
    (checkmk_agent_edition == "cee" or
    checkmk_agent_edition == "cce" or
    checkmk_agent_edition == "cfe" or
    checkmk_agent_edition == "cme")
    and checkmk_agent_host_specific | bool
  tags:
    - install-package

- name: "{{ ansible_os_family }} Derivatives: Download folder-specific Checkmk {{ checkmk_agent_edition | upper }} Agent."
  ansible.windows.win_get_url:
    url: "{{ checkmk_agent_agent.url.cee }}?os_type=windows_msi&agent_type=generic&folder_name={{ checkmk_agent_folder }}"
    validate_certs: "{{ checkmk_agent_server_validate_certs | bool }}"
    dest: "{{ checkmk_agent_agent.file.cee }}"
    method: GET
    headers:
      Authorization: "Bearer {{ checkmk_agent_user }} {{ checkmk_agent_auth }}"
      Accept: "application/octet-stream"
  register: checkmk_agent_folder_download_state
  when: |
    (checkmk_agent_edition == "cee" or
    checkmk_agent_edition == "cce" or
    checkmk_agent_edition == "cfe" or
    checkmk_agent_edition == "cme")
    and checkmk_agent_folder is defined
    and not checkmk_agent_host_specific | bool
  retries: 3
  failed_when: 'false'
  changed_when: checkmk_agent_folder_download_state.status_code is defined and checkmk_agent_folder_download_state.status_code == 200
  delegate_to: "{{ checkmk_agent_delegate_download }}"
  tags:
    - download-package

- name: "Set Fact: Agent State: folder-specific."
  ansible.builtin.set_fact:
    checkmk_agent_folder_specific: >-
      {{ (checkmk_agent_folder_download_state.status_code is defined and checkmk_agent_folder_download_state.status_code == 200) | bool }}

- name: "{{ ansible_os_family }}: Download GENERIC Checkmk {{ checkmk_agent_edition | upper }} Agent."
  ansible.windows.win_get_url:
    url: "{{ checkmk_agent_agent.url.cee }}?os_type=windows_msi&agent_type=generic"
    validate_certs: "{{ checkmk_agent_server_validate_certs | bool }}"
    dest: "{{ checkmk_agent_agent.file.cee }}"
    method: GET
    headers:
      Authorization: "Bearer {{ checkmk_agent_user }} {{ checkmk_agent_auth }}"
      Accept: "application/octet-stream"
  when: |
    (checkmk_agent_edition == "cee" or
    checkmk_agent_edition == "cce" or
    checkmk_agent_edition == "cfe" or
    checkmk_agent_edition == "cme")
    and not (checkmk_agent_host_specific | bool or checkmk_agent_folder_specific | bool)
  retries: 3
  delegate_to: "{{ checkmk_agent_delegate_download }}"
  tags:
    - download-package

- name: "{{ ansible_os_family }}: Install GENERIC or folder-specific  Checkmk {{ checkmk_agent_edition | upper }} Agent."
  ansible.windows.win_package:
    path: "{{ checkmk_agent_agent.file.cee }}"
    state: present
  when: |
    (checkmk_agent_edition == "cee" or
    checkmk_agent_edition == "cce" or
    checkmk_agent_edition == "cfe" or
    checkmk_agent_edition == "cme")
    and not checkmk_agent_host_specific | bool
  tags:
    - install-package

- name: "{{ ansible_os_family }}: Install Checkmk CRE Agent."
  ansible.windows.win_package:
    path: "{{ checkmk_agent_agent.file.cre }}"
    state: present
  when: checkmk_agent_edition == "cre"
  tags:
    - install-package
