---
# Provice the URL and credentials to your Checkmk site here #
# server_url: "http://192.168.56.162/"
# site: "frimo"
server_url: "http://127.0.0.1:3080/"
site: "cmk"
automation_user: "cmkadmin"
automation_secret: "cmk"
checkmk_agent_user: "{{ automation_user }}"
checkmk_agent_pass: "{{ automation_secret }}"

checkmk_version: "2.1.0p26"
checkmk_edition: "cee"
#############################################################

# Hosts #####################################################
checkmk_folders:
  - path: /test
    name: Test
  - path: /foo/
    name: Foo
  - path: /bar
    name: Bar
  - path: /foo/bar
    name: Bar
  - path: /bar/foo
    name: Foo
  - path: /foo/bar/treasure
    name: Treasure
#############################################################
