---
# Provice the URL and credentials to your Checkmk site here #
server_url: "http://localhost/"
site: "my_site"
automation_user: "cmkadmin"
automation_secret: "cmk"
checkmk_agent_user: "{{ automation_user }}"
checkmk_agent_pass: "{{ automation_secret }}"

checkmk_version: "2.1.0p21"
checkmk_edition: "cre"
#############################################################

# Hosts #####################################################
checkmk_folders:
  - path: /test
    name: Test
  - path: /foo/
    name: Foo
  - path: /bar
    name: Bar
  - path: /foo/bar
    name: Bar
  - path: /bar/foo
    name: Foo
  - path: /foo/bar/treasure
    name: Treasure
#############################################################

# Contact Groups ############################################
checkmk_contact_groups:
  - name: "server"
    title: "Server"
  - name: "linux"
  - name: "windows"
  - name: "Network"
    title: "Network Admins"
  - name: "managers"
    title: "Managers"
#############################################################

# Users #####################################################
checkmk_users:
  - name: user1
    fullname: User Eins
    password: "123"
    newpassword: "abc"
    auth_type: password
    email: 123@company.com
    contactgroups:
      - server
    fallback_contact: true
  - name: user2
    fullname: User Zwei
    password: "234"
    newpassword: "bcd"
    auth_type: password
    email: 234@company.com
    contactgroups:
      - linux
    fallback_contact: true
  - name: user3
    fullname: User Drei
    password: "345"
    newpassword: "cde"
    auth_type: password
    email: 345@company.com
    contactgroups:
      - network
    fallback_contact: false
#############################################################

#############################################################
