---
checkmk_folders:
  - path: /test
    name: Test
  - path: /foo/
    name: Foo
  - path: /bar
    name: Bar
  - path: /foo/bar
    name: Bar
  - path: /bar/foo
    name: Foo
  - path: /foo/bar/treasure
    name: Treasure

checkmk_folder:
    name: "Folder 1"
    path: "/folder1"
    criticality: "test"

