---
# General
checkmk_version: "2.1.0p36"
checkmk_edition: "cre"
server_url: "http://127.0.0.1/"
automation_user: "cmkadmin"
automation_secret: "d7589df1"

# Server Role
checkmk_server_edition: "{{ checkmk_edition }}"
checkmk_server_version: "{{ checkmk_version }}"
checkmk_server_verify_setup: 'true'

checkmk_server_configure_firewall: 'false'

checkmk_server_backup_on_update: 'true'  # Not recommended to disable this option
checkmk_server_backup_dir: /tmp
checkmk_server_backup_opts: '--no-past'
checkmk_server_allow_downgrades: 'true'

checkmk_server_sites:
  - name: "started"
    version: "{{ checkmk_version }}"
    state: started
    admin_pw: "{{ automation_secret }}"
    update_conflict_resolution: install
    omd_auto_restart: 'true'
    omd_config:
      - var: LIVESTATUS_TCP
        value: "on"
      - var: LIVESTATUS_TCP_PORT
        value: "6557"
  - name: "stopped"
    version: "{{ checkmk_version }}"
    state: stopped
    admin_pw: "{{ automation_secret }}"
    update_conflict_resolution: install
  - name: "enabled"
    version: "{{ checkmk_version }}"
    state: enabled
    admin_pw: "{{ automation_secret }}"
    update_conflict_resolution: install
    omd_auto_restart: 'true'
    omd_config:
      - var: AUTOSTART
        value: "on"
  - name: "disabled"
    version: "{{ checkmk_version }}"
    state: disabled
    admin_pw: "{{ automation_secret }}"
    update_conflict_resolution: install
    omd_auto_restart: 'false'
    omd_config:
      - var: AUTOSTART
        value: "off"
  - name: "present"
    version: "{{ checkmk_version }}"
    state: present
    admin_pw: "{{ automation_secret }}"
    update_conflict_resolution: install
    omd_auto_restart: 'false'
    omd_config:
      - var: LIVESTATUS_TCP
        value: "on"
  - name: "absent"
    version: "{{ checkmk_version }}"
    state: absent
    admin_pw: "{{ automation_secret }}"
    update_conflict_resolution: install
