---

- name: "create host {{ inventory_hostname }} with admin-ip {{ management_ip }}"
  tribe29.checkmk.host:
    server_url: "{{ checkmk_server.url }}"
    site: "{{ checkmk_server.site }}"
    automation_user: "{{ checkmk_server.automation_user }}"
    automation_secret: "{{ checkmk_server.automation_secret }}"
    host_name: "{{ inventory_hostname }}"
    folder: "{{ checkmk_server.default_folder }}"
    attributes:
      site: "{{ checkmk_server.site }}"
      ipaddress: "{{ management_ip }}"
    state: 'present'
  delegate_to: "{{ checkmk_server.host }}.{{ checkmk_server.domain }}"
  tags: check_mk_setup_create_host

