---

- name: "create all folders, WIP @(#) - missing idempotency here ... "
  tribe29.checkmk.folder:
    server_url: "{{ checkmk_server.url }}"
    site: "{{ checkmk_server.site }}"
    automation_user: "{{ checkmk_server.automation_user }}"
    automation_secret: "{{ checkmk_server.automation_secret }}"
    path: "{{ folder.path }}"
    name: "{{ folder.name }}"
    state: "present"
  delegate_to: "{{ checkmk_server.host }}.{{ checkmk_server.domain }}"
  loop: "{{ checkmk_server_setup.folders }}"
  loop_control: 
    loop_var: folder
  when: checkmk_server_setup.folders is defined | default(false)
  tags:
    - check_mk_setup_create_folders
