---
- name: "Create folder."
  folder:
    server_url: "{{ server_url }}"
    site: "{{ outer_item.item }}"
    automation_user: "{{ automation_user }}"
    automation_secret: "{{ automation_secret }}"
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    state: "present"
  delegate_to: localhost
  run_once: true  # noqa run-once[task]
  loop: "{{ checkmk_folders }}"
- name: "Create host."
  host:
    server_url: "{{ server_url }}"
    site: "{{ outer_item.item }}"
    automation_user: "{{ automation_user }}"
    automation_secret: "{{ automation_secret }}"
    name: "{{ inventory_hostname }}"
    folder: "{{ checkmk_folder_path }}"
    attributes:
      site: "{{ site }}"
      ipaddress: 127.0.0.1
    state: "present"
  delegate_to: localhost
- name: "Discover services on host."
  discovery:
    server_url: "{{ server_url }}"
    site: "{{ outer_item.item }}"
    automation_user: "{{ automation_user }}"
    automation_secret: "{{ automation_secret }}"
    host_name: localhost
    state: "fix_all"
  delegate_to: localhost
- name: "Activate changes on site."
  activation:
    server_url: "{{ server_url }}"
    site: "{{ outer_item.item }}"
    automation_user: "{{ automation_user }}"
    automation_secret: "{{ automation_secret }}"
    force_foreign_changes: 'true'
    sites:
      - "{{ outer_item.item }}"
  delegate_to: localhost
  run_once: true  # noqa run-once[task]
