---
checkmk_server_server_stable_os:
  - Debian 11
  - Ubuntu 20
  - CentOS 7
  - CentOS 8
  - RHEL 7
  - RHEL 8

checkmk_server_edition: cre
checkmk_server_version: 2.1.0p1
checkmk_server_verify_setup: 'true'

checkmk_server_download_user: []
checkmk_server_download_pass: []

checkmk_server_sites: []
# - name: test
#   version: "{{ checkmk_server_version }}"
#   state: started
#   admin_pw: test
checkmk_server_configure_firewall: 'true'

checkmk_server_backup_on_update: 'true' # Not recommended to disable this option
checkmk_server_backup_dir: /opt/omd/sites/
