---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

  - name: "Test Agent is installed."
    ansible.builtin.stat:
      path: "/usr/lib/check_mk_agent"
    register: checkmk_agent_install_state

  - name: "Verify Agent is installed."
    ansible.builtin.assert:
      that: checkmk_agent_install_state.stat.exists
