---

checkmk_server_setup_file: "check-mk-{{ checkmk_server_edition_mapping[checkmk_server_edition] }}-{{ checkmk_server_version }}-el{{ ansible_distribution_major_version }}-38.x86_64.rpm"   # noqa yaml[line-length]

checkmk_server_ports:
  - 80/tcp
  - 443/tcp
  - 8000/tcp

checkmk_server_prerequisites_per_distro:
  RedHat:
    - firewalld
    - epel-release
    - python3-libsemanage
    - dnf-plugins-core
  RedHat-7:
    - firewalld
    - epel-release
    - libsemanage-python
    - yum-plugins-core
  RedHat-8:
    - firewalld
    - epel-release
    - python3-libsemanage
    - dnf-plugins-core

checkmk_server_prerequisites: "{{ checkmk_server_prerequisites_per_distro[ansible_facts.os_family ~ '-' ~ ansible_facts.distribution_major_version] | default(
  checkmk_server_prerequisites_per_distro[ansible_facts.os_family]) }}"
