---
- name: "Install Checkmk Prerequisites."
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ checkmk_server_prerequisites }}"
  tags:
    - install-package
    - install-prerequisites

- name: "Install Checkmk Server."
  become: true
  ansible.builtin.apt:
    deb: "/tmp/{{ checkmk_server_setup_file }}"
    update_cache: 'yes'
    state: present
  tags:
    - install-package
