---
- name: "Install Checkmk Prerequisites."
  become: true
  ansible.builtin.yum:
    name: "{{ checkmk_server_prerequisites }}"
    state: present
  tags:
    - install-package
    - install-prerequisites

- name: "Enable powertools repository."
  become: true
  ansible.builtin.shell: dnf config-manager --set-enabled powertools  # noqa command-instead-of-shell
  when: ansible_distribution_major_version == "8"
  tags:
    - enable-powertools

- name: "Install Checkmk Server."
  become: true
  ansible.builtin.yum:
    name: "/tmp/{{ checkmk_server_setup_file }}"
    state: present
    disable_gpg_check: '{{ not checkmk_server_verify_setup | bool }}'
  tags:
    - install-package

- name: "Enable httpd can network connect selinux boolean."
  become: true
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
  when: ansible_facts.selinux.status == 'enabled'
  tags:
    - set-selinux-boolean

- name: "Open firewall ports."
  become: true
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ checkmk_server_ports }}"
  when: checkmk_server_configure_firewall | bool
