---
- name: "Enable powertools repository."
  become: 'yes'
  ansible.builtin.shell: dnf config-manager --set-enabled powertools
  when: ansible_distribution_major_version == "8"

- name: "Install Checkmk Server."
  become: 'yes'
  ansible.builtin.yum:
    name: "/tmp/{{ checkmk_server_setup_file }}"
    state: present
    disable_gpg_check: '{{ not checkmk_server_verify_setup | bool }}'

- name: "Enable httpd can network connect selinux boolean."
  become: 'yes'
  seboolean: 
    name: httpd_can_network_connect 
    state: yes 
    persistent: yes

- name: "Get service facts."
  ansible.builtin.service_facts:
  register: services_state

- name: "Open port 80 for httpd."
  become: 'yes'
  ansible.posix.firewalld:
    service: http
    permanent: 'yes'
    immediate: 'yes'
    state: enabled
  when: services_state.ansible_facts.services['firewalld.service']['state'] == 'running'
