---
- name: "Install libsemanage-python."
  become: 'yes'
  ansible.builtin.shell: dnf config-manager --set-enabled powertools
  when: ansible_distribution_major_version == "8"

- name: "Install Checkmk Server."
  become: 'yes'
  ansible.builtin.yum:
    name: "/tmp/{{ checkmk_server_setup_file }}"
    state: present
    disable_gpg_check: '{{ not checkmk_server_verify_setup | bool }}'

- name: "Install libsemanage-python."
  become: 'yes'
  ansible.builtin.yum: 
    name: libsemanage-python
    state: installed
  when: ansible_distribution_major_version == "7"

- name: "Install libsemanage-python."
  become: 'yes'
  ansible.builtin.yum: 
    name: python3-libsemanage
    state: installed
  when: ansible_distribution_major_version == "8"

- name: "Enable httpd can network connect selinux boolean."
  become: 'yes'
  seboolean: 
    name: httpd_can_network_connect 
    state: yes 
    persistent: yes

- name: "Open port 80 for httpd."
  become: 'yes'
  ansible.posix.firewalld:
    service: http
    permanent: 'yes'
    immediate: 'yes'
    state: enabled
