---
- name: "Create Sites."
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    omd -V {{ item.version }}.{{ checkmk_server_edition }} create {{ item.name }}
  args:
    executable: /bin/bash
    creates: "/omd/sites/{{ item.name }}"
  no_log: true
  loop: "{{ checkmk_server_sites }}"
  when: item.state != "absent"
  register: checkmk_server_sites_created

- name: "Update Sites."
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    if [[ "$(omd version {{ item.name }} | egrep -o '[^ ]+$')" < "{{ item.version }}.{{ checkmk_server_edition }}" ]]
      then
        omd stop {{ item.name }}
        omd -f -V {{ item.version }}.{{ checkmk_server_edition }} update --conflict {{ item.update_conflict_resolution }} {{ item.name }} 
      else
        echo "already up to date or version given is older than current."
    fi
  args:
    executable: /bin/bash
  loop: "{{ checkmk_server_sites }}"
  changed_when: "'already up to date or version given is older than current.' not in checkmk_server_sites_updated.stdout"
  when: item.state != "absent" and item.update_conflict_resolution is defined
  register: checkmk_server_sites_updated

- name: "Start Sites."
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    omd start {{ item.name }}
  args:
    executable: /bin/bash
    creates: "/opt/omd/sites/{{ item.name }}/tmp/run/live"
  no_log: true
  loop: "{{ checkmk_server_sites }}"
  when: item.state == "started"
  register: checkmk_server_sites_started

- name: "Stop Sites."
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    omd stop {{ item.name }}
  args:
    executable: /bin/bash
    removes: "/opt/omd/sites/{{ item.name }}/tmp/run/live"
  no_log: true
  loop: "{{ checkmk_server_sites }}"
  when: (item.state == "absent") or (item.state == "stopped")
  register: checkmk_server_sites_stopped

- name: "Destroy Sites."
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    (yes yes || true) | omd rm {{ item.name }}
  args:
    executable: /bin/bash
    removes: "/omd/sites/{{ item.name }}"
  # no_log: true
  loop: "{{ checkmk_server_sites }}"
  when: item.state == "absent"
  register: checkmk_server_sites_removed

- name: "Update Site Admin Password."
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    echo '{{ item.admin_pw }}' | htpasswd -i /omd/sites/{{ item.name }}/etc/htpasswd cmkadmin
  args:
    executable: /bin/bash
  no_log: true
  loop: "{{ checkmk_server_sites }}"
  when: item.state != "absent"

