---
- name: "Showcase contact_group and user modules."
  hosts: test
  gather_facts: 'no'
  vars_files:
    - ../vars/auth.yml      # This vars file contains details about your site
    - ../vars/groups.yml    # This vars file contains the contact groups
    - ../vars/users.yml     # This vars file contains the user to manage
  tasks:
    - name: "Create contact groups."
      contact_group:
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        name: "{{ item.name }}"
        title: "{{ item.title | default(item.name) }}"
        state: "present"
      delegate_to: localhost
      run_once: true
      loop: "{{ checkmk_contact_groups }}"

    - name: "Create users."
      user:
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        name: "{{ item.name }}"
        fullname: "{{ item.fullname }}"
        auth_type: "{{ item.auth_type }}"
        password: "{{ item.password }}"
        roles:
          - "guest"
        authorized_sites:
          - "{{ site }}"
        state: "present"
      delegate_to: localhost
      run_once: true
      loop: "{{ checkmk_users }}"

    - name: "Pause to review first set of changes."
      ansible.builtin.pause:
        prompt: |
          "Feel free to review the changes in your Checkmk site: {{ site }}."
          "Press <Enter> to continue."

    - name: "Activate changes on site."
      activation:
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        force_foreign_changes: 'true'
        sites:
          - "{{ site }}"
      delegate_to: localhost
      run_once: 'true'

    - name: "Delete users."
      user:
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        name: "{{ item.name }}"
        state: "absent"
      delegate_to: localhost
      run_once: true
      loop: "{{ checkmk_users }}"

    - name: "Delete contact groups."
      contact_group:
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        name: "{{ item.name }}"
        state: "absent"
      delegate_to: localhost
      run_once: true
      loop: "{{ checkmk_contact_groups }}"

    - name: "Pause to review second set of changes."
      ansible.builtin.pause:
        prompt: |
          "Feel free to review the changes in your Checkmk site: {{ site }}."
          "Press <Enter> to continue."

    - name: "Activate changes on site."
      activation:
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        force_foreign_changes: 'true'
        sites:
          - "{{ site }}"
      delegate_to: localhost
      run_once: 'true'
