---
My_Site:
  hosts:
    win10:
      ansible_host: 192.168.128.101
      checkmk_agent_host_attributes:
        ipaddress: '{{ansible_host}}'
    win11:
      ansible_host: 192.168.128.100
      checkmk_agent_host_attributes:
        ipaddress: '{{ansible_host}}'
    win2k12:
      ansible_host: 192.168.128.103
      checkmk_agent_host_attributes:
        ipaddress: '{{ansible_host}}'
    win2k16:
      ansible_host: 192.168.128.102
      checkmk_agent_host_attributes:
        ipaddress: '{{ansible_host}}'
    win2k19:
      ansible_host: 192.168.128.105
      checkmk_agent_host_attributes:
        ipaddress: '{{ansible_host}}'
    win2k22:
      ansible_host: 192.168.128.104
      checkmk_agent_host_attributes:
        ipaddress: '{{ansible_host}}'

  vars:
    checkmk_agent_add_host: true
    checkmk_agent_discover: true
    checkmk_agent_edition: cre
    checkmk_agent_host_ip: '{{ ansible_host }}'
    checkmk_agent_host_name: '{{ inventory_hostname }}'
    checkmk_agent_user: automation
    checkmk_agent_pass: $AUTOMATION_SECRET
    checkmk_agent_protocol: http
    checkmk_agent_server: 127.0.0.1
    checkmk_agent_port: 80
    checkmk_agent_site: My_Site
    checkmk_agent_version: 2.0.0p22
    ansible_user: Administrator
    ansible_password: $SECRET
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
