- name: "Test all modules."
  hosts: all
  gather_facts: 'no'
  vars_files:
    - ./vars/site.yml
  tasks:
  - name: "Run activation module - 1."
    activation:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      force_foreign_changes: 'true'
      sites: "test"
    delegate_to: localhost
    run_once: 'true'

  - name: "Create folders."
    folder:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      path: "{{ item.path }}"
      title: "{{ item.title }}"
      state: "present"
    register: testout
    delegate_to: localhost
    run_once: 'yes'
    loop: "{{ checkmk_folders }}"

  - name: "Create hosts."
    host:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      host_name: "{{ inventory_hostname }}"
      folder: "{{ checkmk_folder_path }}"
      state: "present"
    delegate_to: localhost

  - name: "Run activation module - 2."
    activation:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      force_foreign_changes: 'true'
      sites: "test"
    delegate_to: localhost
    run_once: 'true'

  - name: "Delete Hosts."
    host:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      host_name: "{{ inventory_hostname }}"
      folder: "{{ checkmk_folder_path }}"
      state: "absent"
    delegate_to: localhost

  - name: "Delete folders."
    folder:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      path: "{{ item.path }}"
      title: "{{ item.title }}"
      state: "absent"
    register: testout
    delegate_to: localhost
    run_once: 'yes'
    loop: "{{ checkmk_folders }}"

  - name: "Run activation module - 3."
    activation:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      force_foreign_changes: 'true'
      sites: "test"
    delegate_to: localhost
    run_once: 'true'
