---
- name: "Test user module."
  hosts: all
  gather_facts: 'no'
  vars_files:
    - ./vars/config.yml
<<<<<<< HEAD
=======
      #- ./vars/users.yml
>>>>>>> 04a61c9 (Continuously developing the user.py)
  tasks:
    - name: "Activate changes on site - 1."
      activation:
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        force_foreign_changes: 'true'
        sites:
          - "{{ site }}"
      delegate_to: localhost
      run_once: 'true'

    - name: "Create users."
      cmk_user:  # noqa fqcn-builtins
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        name: "{{ item.name }}"
        fullname: "{{ item.fullname }}"
        auth_type: "{{ item.auth_type }}"
<<<<<<< HEAD
        password: "{{ item.password }}"
=======
>>>>>>> 04a61c9 (Continuously developing the user.py)
        roles:
          - "admin"
        authorized_sites:
          - "{{ site }}"
        state: "present"
      register: testout
      delegate_to: localhost
      run_once: 'yes'
      loop: "{{ checkmk_users }}"

    - name: "Activate changes on site - 2."
      activation:
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        force_foreign_changes: 'true'
        sites:
          - "{{ site }}"
      delegate_to: localhost
      run_once: 'true'

    - name: "Edit users."
      cmk_user:  # noqa fqcn-builtins
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        name: "{{ item.name }}"
        contactgroups: "{{ item.contactgroups }}"
        state: "present"
      register: testout
      delegate_to: localhost
      run_once: 'yes'
      loop: "{{ checkmk_users }}"

    - name: "Activate changes on site - 3."
      activation:
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        force_foreign_changes: 'true'
        sites:
          - "{{ site }}"
      delegate_to: localhost
      run_once: 'true'

<<<<<<< HEAD
    - name: "Reset password of users."
=======
    - name: "Delete users."
>>>>>>> 04a61c9 (Continuously developing the user.py)
      cmk_user:  # noqa fqcn-builtins
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        name: "{{ item.name }}"
        password: "{{ item.newpassword }}"
        state: "reset_password"
      register: testout
      delegate_to: localhost
      run_once: 'yes'
      loop: "{{ checkmk_users }}"

    - name: "Activate changes on site - 4."
      activation:
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        force_foreign_changes: 'true'
        sites:
          - "{{ site }}"
      delegate_to: localhost
      run_once: 'true'

    - name: "Delete users."
      cmk_user:  # noqa fqcn-builtins
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        name: "{{ item.name }}"
        state: "absent"
      register: testout
      delegate_to: localhost
      run_once: 'yes'
      loop: "{{ checkmk_users }}"

    - name: "Activate changes on site - 5."
      activation:
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        force_foreign_changes: 'true'
        sites:
          - "{{ site }}"
      delegate_to: localhost
      run_once: 'true'
