---
- name: "Test user module."
  hosts: all
  gather_facts: 'no'
  vars_files:
    - ./vars/config.yml
  tasks:
    - name: "Create users."
      cmk_user:  # noqa fqcn-builtins
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        name: "{{ item.name }}"
        fullname: "{{ item.fullname }}"
        auth_type: "{{ item.auth_type }}"
        password: "{{ item.password }}"
        roles:
          - "admin"
        authorized_sites:
          - "{{ site }}"
        state: "present"
      register: testout
      delegate_to: localhost
      run_once: 'yes'
      loop: "{{ checkmk_users }}"

    - name: "Create same users again."
      cmk_user:  # noqa fqcn-builtins
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        name: "{{ item.name }}"
        fullname: "{{ item.fullname }}"
        auth_type: "{{ item.auth_type }}"
        password: "{{ item.password }}"
        roles:
          - "admin"
        authorized_sites:
          - "{{ site }}"
        state: "present"
      register: testout
      delegate_to: localhost
      run_once: 'yes'
      loop: "{{ checkmk_users }}"

    - name: "Edit users."
      cmk_user:  # noqa fqcn-builtins
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        name: "{{ item.name }}"
        contactgroups: "{{ item.contactgroups }}"
        state: "present"
      register: testout
      delegate_to: localhost
      run_once: 'yes'
      loop: "{{ checkmk_users }}"

    - name: "Edit users - again."
      cmk_user:  # noqa fqcn-builtins
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        name: "{{ item.name }}"
        contactgroups: "{{ item.contactgroups }}"
        state: "present"
      register: testout
      delegate_to: localhost
      run_once: 'yes'
      loop: "{{ checkmk_users }}"

    - name: "Reset password of users."
      cmk_user:  # noqa fqcn-builtins
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        name: "{{ item.name }}"
        password: "{{ item.newpassword }}"
        state: "reset_password"
      register: testout
      delegate_to: localhost
      run_once: 'yes'
      loop: "{{ checkmk_users }}"

    - name: "Delete users."
      cmk_user:  # noqa fqcn-builtins
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        name: "{{ item.name }}"
        state: "absent"
      register: testout
      delegate_to: localhost
      run_once: 'yes'
      loop: "{{ checkmk_users }}"
