---
checkmk_agent_version: "2.0.0p24"
checkmk_agent_edition: cre
checkmk_agent_protocol: http
checkmk_agent_server: localhost
checkmk_agent_site: my_site
checkmk_agent_update: 'false'
checkmk_agent_tls: 'false'
