---
checkmk_agent_version: "2.1.0p1"
checkmk_agent_edition: cre
checkmk_agent_protocol: http
checkmk_agent_server: localhost
checkmk_agent_site: my_site
checkmk_agent_update: 'false'
checkmk_agent_tls: 'false'
checkmk_agent_prep_legacy: 'false'
