---
checkmk_agent_version: "2.1.0p1"
checkmk_agent_edition: cre
checkmk_agent_protocol: http
checkmk_agent_server: localhost
checkmk_agent_site: my_site
checkmk_agent_add_host: 'false'
checkmk_agent_update: 'false'
checkmk_agent_tls: 'false'
checkmk_agent_change_firewall: 'false'
checkmk_agent_prep_legacy: 'false'
checkmk_agent_discover: 'false'
checkmk_agent_delegate_api_calls: localhost
checkmk_agent_host_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
checkmk_agent_host_name: "{{ hostvars[inventory_hostname]['ansible_fqdn'] }}"
