---
name: Release Collection
on: # yamllint disable-line rule:truthy
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current version
        id: current_version
        run: echo "::set-output name=version::$(grep 'version:' galaxy.yml | cut -d ' ' -f 2)"

      - name: Set up Python.
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Compile Collection Changelog
        run: antsibull-changelog release

      - name: Compile Collection Docs
        run: antsibull-docs collection --use-current --squash-hierarchy --dest-dir ./docs/ tribe29.checkmk
