env:
  NAMESPACE: checkmk
  COLLECTION_NAME: general
  CONTAINER_NAME: "ansible-checkmk-test"

name: Build Test Container Images
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  push:
    paths:
      - 'tests/container/**'
    branches:
      - "build/integration-tests-docker"

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build Container

    steps:
      - name: "Check out code"
        uses: actions/checkout@v4
        with:
          path: ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: "Install ansible-base devel"
        run: pip install https://github.com/ansible/ansible/archive/devel.tar.gz --disable-pip-version-check

      - name: "Docker Build"
        run: docker build -t ${{ env.CONTAINER_NAME }} ./ --build-arg DL_USER=d-gh-ansible-dl --build-arg DL_PW=${{ secrets.CHECKMK_DOWNLOAD_PW }}
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}/tests/container

      - name: "Docker Save"
        run: docker save ${{ env.CONTAINER_NAME }}:latest > ./${{ env.CONTAINER_NAME }}-latest-image.tar.gz
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}/tests/container

      - name: "Upload Artifact"
        run: CLOUDSEND_PASSWORD=${{ secrets.NEXTCLOUD_PW }} ./scripts/cloudsend/cloudsend.sh -e ./tests/container/${{ env.CONTAINER_NAME }}-latest-image.tar.gz $(CLOUD_SHARE)
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}
        env:
          NEXTCLOUD_PW: ${{ secrets.NEXTCLOUD_PW }}
          CLOUDSEND_PASSWORD: ${{ secrets.NEXTCLOUD_PW }}

      - name: "Run integration test for testing"
        run: ansible-test integration activation -v --color --retry-on-error --continue-on-error --diff --python 3.11 --docker-privileged ${{ env.CONTAINER_NAME }}
        working-directory: ./ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}
