---
name: Ansible Collection Integration Tests
on: # yamllint disable-line rule:truthy
  push:
    branches:    
    - 'main'
    - 'devel'

jobs:
  ansible-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.6, 2.7, 3.5, 3.6, 3.7, 3.8, 3.9, 3.10]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies.
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Copy Files and Directories to Source
        run: |
          mkdir -p ansible_collections/$namespace/$collection/
          cp $files ansible_collections/$namespace/$collection/
          cp -rf $directories ansible_collections/$namespace/$collection/
        env:
          # Keep in sync with release.yaml!
          files: "README.md ansible.cfg galaxy.yml"
          directories: "changelogs docs meta playbooks plugins"
          namespace: "tribe29"
          collection: "checkmk"

      - name: Run Sanity Checks.
        run: cd ansible_collections/$namespace/$collection/ && ansible-test integration
        env:
          namespace: "tribe29"
          collection: "checkmk"

# ToDo: Automatically raise issue?
