name: "Labeler"
on:
  workflow_dispatch:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:

  issues:
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    steps:
    - name: "Label Issues."
      uses: github/issue-labeler@v3.1
      with:
        configuration-path: .github/labeler.yml
        include-title: 1
        include-body: 0
        repo-token: ${{ github.token }}

  pulls:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout code."
      uses: actions/checkout@v3
      with:
        path: ansible_collections/${{env.NAMESPACE}}/${{env.COLLECTION_NAME}}
    - name: "Label Pull Requests."
      uses: actions/labeler@v4
