name: "Labeler"
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  issues:
    permissions:
      issues: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v3.1
      with:
        configuration-path: .github/labeler.yml
        include-title: 1
        include-body: 0

  pulls:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
