---
name: Release new Collection Version
on: # yamllint disable-line rule:truthy
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current version
        id: current_version
        run: echo "::set-output name=version::$(grep 'version:' galaxy.yml | cut -d ' ' -f 2)"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Compile Collection Changelog
        run: antsibull-changelog release

      - name: Commit build changelogs
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git checkout -B changelogs-compile
          git add -f changelogs/ CHANGELOG.rst
          git commit -m "Add built front-end assets"
          git push -f origin changelogs-compile
      
      - name: Merge changelogs back into devel
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: devel
          github_token: ${{ github.token }}

      - name: Copy Files and Directories to Source
        run: |
          mkdir -p build/src
          cp $files build/src
          cp -rf $directories build/src
        env:
          files: "CHANGELOG.rst LICENSE README.md ansible.cfg galaxy.yml"
          # directories: "playbooks plugins roles vars"
          directories: "changelogs docs meta playbooks plugins"

      - name: Build Ansible Collection
        run: ansible-galaxy collection build build/src --force

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.current_version.outputs.version }}
          release_name: Release v${{ steps.current_version.outputs.version }}
          body: |
            # Ansible Collection: tribe29.checkmk

            You can install this collection locally as follows, if you download
            the tarball from this release:

                ansible-galaxy collection install /path/to/tribe29-checkmk-${{ steps.current_version.outputs.version }}.tar.gz

            You can also include it in a `requirements.yml` file using the format:
            ```yaml
            ---
            collections:
              - source: /path/to/tribe29-checkmk-${{ steps.current_version.outputs.version }}.tar.gz
                type: file
            ```
            and install it with `ansible-galaxy collection install -r requirements.yml`.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: tribe29-checkmk-${{ steps.current_version.outputs.version }}.tar.gz
          asset_name: tribe29-checkmk-${{ steps.current_version.outputs.version }}.tar.gz
          asset_content_type: application/tar+gzip

      # - name: changelogs-compile Ansible collection to Galaxy
      #   run: ansible-galaxy collection publish tribe29-checkmk-${{ steps.current_version.outputs.version }}.tar.gz --api-key ${{ secrets.GALAXY_API_KEY }}

      - name: Delete changelogs-compile branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          branches: changelogs-compile
